import initScrollSuave from "./modules/scroll-suave.js";
import initAnimaScroll from "./modules/anima-scroll.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/init-tab.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initMenuDropdown from "./modules/menu-dropdown.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initAnimaNumeros from "./modules/animaNumeros.js";
import initFuncionamento from "./modules/hora-funcionamento.js";

initScrollSuave();
initAnimaScroll();
initAccordion();
initTabNav();
initModal();
initTooltip();
initMenuDropdown();
initMenuMobile();
initAnimaNumeros();
initFuncionamento();
